### ISSUE TITLE
KeyError: 'addressList'

### ISSUE THREAD

**Issue by hubery05** [zhou-xiaojun/jd_mask#17]
2020-03-07 10:00:01,785 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100011521400&sn=0d04f2fe2c3d22349567ddffc347ca22&from=pc
2020-03-07 10:00:01,785 INFO: 访问商品的抢购连接...
2020-03-07 10:00:01,957 INFO: 访问抢购订单结算页面...
2020-03-07 10:00:02,110 INFO: 生成提交抢购订单所需参数...
2020-03-07 10:00:02,111 INFO: 获取秒杀初始化信息...
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'

**Comment by littlewhitelyw** [comment]
遇到了同样的问题，请问解决了吗？

**Comment by else05** [comment]
cookie 问题  ，失效了
