### ISSUE TITLE
运费券是啥机制呀?

### ISSUE THREAD

**Issue by yaosonglive** [zhou-xiaojun/jd_mask#21]
第一次抢的时候自动用了运费券，后面就不用了

**Comment by hubery05** [comment]
能发下你的整个代码包吗，我每次都是：
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'

**Comment by littlewhitelyw** [comment]
> 能发下你的整个代码包吗，我每次都是：
> Traceback (most recent call last):
> File "main.py", line 22, in
> start_tool.submit_seckill_order()
> File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
> self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
> File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
> default_address = init_info['addressList'][0] # 默认地址dict
> KeyError: 'addressList'

遇到了同样的问题，请问解决了吗？

**Comment by else05** [comment]
> 能发下你的整个代码包吗，我每次都是：
> Traceback (most recent call last):
> File "main.py", line 22, in
> start_tool.submit_seckill_order()
> File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
> self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
> File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
> default_address = init_info['addressList'][0] # 默认地址dict
> KeyError: 'addressList'

你这个是cookie无效吧，你控制台显示的用户是不是jd???  ,如果是就错了

**Comment by else05** [comment]
> > 能发下你的整个代码包吗，我每次都是：
> > Traceback (most recent call last):
> > File "main.py", line 22, in
> > start_tool.submit_seckill_order()
> > File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
> > self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
> > File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
> > default_address = init_info['addressList'][0] # 默认地址dict
> > KeyError: 'addressList'
> 
> 遇到了同样的问题，请问解决了吗？

cookie 问题

**Comment by yaosonglive** [comment]
> > > 能发下你的整个代码包吗，我每次都是：
> > > Traceback (most recent call last):
> > > File "main.py", line 22, in
> > > start_tool.submit_seckill_order()
> > > File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 237, in submit_seckill_order
> > > self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
> > > File "C:\Users\Hubery\jd_mask\jd_mask_spider_requests.py", line 189, in _get_seckill_order_data
> > > default_address = init_info['addressList'][0] # 默认地址dict
> > > KeyError: 'addressList'
> > 
> > 
> > 遇到了同样的问题，请问解决了吗？
> 
> cookie 问题

对，返回的未登录。
