### ISSUE TITLE
获取秒杀初始化信息报错

### ISSUE THREAD

**Issue by LinkChung** [zhou-xiaojun/jd_mask#23]
2020-03-10 20:00:22,464 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100011551632&sn=df78486818ac6f7638acd3592098a390&from=pc
2020-03-10 20:00:22,464 INFO: 访问商品的抢购连接...
2020-03-10 20:00:22,648 INFO: 访问抢购订单结算页面...
2020-03-10 20:00:22,877 INFO: 生成提交抢购订单所需参数...
2020-03-10 20:00:22,877 INFO: 获取秒杀初始化信息...
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 235, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 185, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 177, in _get_seckill_init_info
    return parse_json(resp.text)
  File "C:\Users\Administrator\Desktop\jd_mask-master\util.py", line 63, in parse_json
    return json.loads(s[begin:end])
  File "C:\Program Files\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LinkChung** [comment]
刚接触python  请问各位大佬这是什么情况啊  参数都是10分钟内刚更新的

**Comment by mati0813** [comment]
我也是这个错误，请问各位大神是什么原因？
