### ISSUE TITLE
获取秒杀初始化信息报错  每次都这样 

### ISSUE THREAD

**Issue by LinkChung** [zhou-xiaojun/jd_mask#24]
2020-03-10 20:00:22,464 INFO: 访问商品的抢购连接...
2020-03-10 20:00:22,648 INFO: 访问抢购订单结算页面...
2020-03-10 20:00:22,877 INFO: 生成提交抢购订单所需参数...
2020-03-10 20:00:22,877 INFO: 获取秒杀初始化信息...
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 235, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 185, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "C:\Users\Administrator\Desktop\jd_mask-master\jd_mask_spider_requests.py", line 177, in _get_seckill_init_info
    return parse_json(resp.text)
  File "C:\Users\Administrator\Desktop\jd_mask-master\util.py", line 63, in parse_json
    return json.loads(s[begin:end])
  File "C:\Program Files\Python38\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python38\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python38\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by LinkChung** [comment]
刚接触python  参数也是10分钟能刚更新的  各位大佬帮忙康康这是什么情况

**Comment by ylhawj** [comment]
虽然最近不需要抢购口罩，但是发现这个代码可以抢其他的东东，比如说，飞天茅台啥的，😅，
而且根据代码提示，可能是获取秒杀初始化信息失败了，这个信息的获取过程我看了，可以放在抢购之前就获取好，这样反而更好一些。
我就简单改了下，在jd_assistant.py里面加个方法，
    def get_seckill_init_info(self, sku_id):
        if not self.seckill_init_info.get(sku_id):
            self.seckill_init_info[sku_id] = self._get_seckill_init_info(sku_id)
然后在main.py函数里面的抢购函数之前调用一下。
目前抢购连接能获取到，其他的也没啥毛病，就是提交订单一直都是失败的，😅。。。可能是货太少了的缘故。
