### ISSUE TITLE
PyCharm显示这个

### ISSUE THREAD

**Issue by BlackDream0754** [zhou-xiaojun/jd_mask#43]
Traceback (most recent call last):
  File "C:/Users/Lumoureni/京东/jd_seckill-master/main.py", line 2, in <module>
    from jd_spider_requests import JdSeckill
  File "C:\Users\Lumoureni\京东\jd_seckill-master\jd_spider_requests.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by xu814077592** [comment]
Python你没下载requests库，  去系统cmd 里 pip install requests
