### ISSUE TITLE
运行main.py报错

### ISSUE THREAD

**Issue by wanggood1** [zhou-xiaojun/jd_mask#44]
Traceback (most recent call last):
  File "C:/Users/Wsuguji/Desktop/jd_seckill-master/main.py", line 2, in <module>
    import jd_spider_requests
  File "C:\Users\Wsuguji\Desktop\jd_seckill-master\jd_spider_requests.py", line 9, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'

**Comment by wuhuinan47** [comment]
pip install lxml
