### ISSUE TITLE
获取秒杀初始化信息... 这一步异常了，报KeyError: 'addressList'

### ISSUE THREAD

**Issue by else05** [zhou-xiaojun/jd_mask#6]
```
2020-02-27 10:00:05,058 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=xxxxxxx&sn=xxxxxx&from=pc
2020-02-27 10:00:05,058 INFO: 访问商品的抢购连接...
2020-02-27 10:00:07,732 INFO: 访问抢购订单结算页面...
2020-02-27 10:00:09,034 INFO: 生成提交抢购订单所需参数...
2020-02-27 10:00:09,035 INFO: 获取秒杀初始化信息...
Traceback (most recent call last):
  File "E:/CodeHub/jd_mask/main.py", line 22, in <module>
    start_tool.submit_seckill_order()
  File "E:\CodeHub\jd_mask\jd_mask_spider_requests.py", line 235, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "E:\CodeHub\jd_mask\jd_mask_spider_requests.py", line 187, in _get_seckill_order_data
    default_address = init_info['addressList'][0]  # 默认地址dict
KeyError: 'addressList'
```

**Comment by huanggx** [comment]
刚遇到同样的问题。

**Comment by lateautumn4lin** [comment]
哈哈，遇到同样的问题，可惜没把错误打印出来，明天再试试吧

**Comment by ivesyi** [comment]
我碰到过，排查原因是cookie过期了，重新登录获取cookie，确保执行时第一行看到提示登录的用户名是自己京东账户而不是jd（然而至今抢到0次）

**Comment by else05** [comment]
> 我碰到过，排查原因是cookie过期了，重新登录获取cookie，确保执行时第一行看到提示登录的用户名是自己京东账户而不是jd（然而至今抢到0次）

谢谢，确实是没登录成功，cookie有问题
