### ISSUE TITLE
秒杀初始化信息解析异常

### ISSUE THREAD

**Issue by Lv-zhaoyang** [zhou-xiaojun/jd_mask#8]
两个帐号6个窗口抢8点的3个不同口罩，成功抢到一个，2个失败，3个报如下错误，信息没打印，不知道信息内容，明天再看看response信息是什么。

---

2020-03-01 19:33:41,857 INFO: 商品名称:【袋鼠医生其他】袋鼠医生（DR.ROOS）医用外科口罩 口罩 10只/包 3层无菌挂耳【行情 报价 价格 评测】-京东
2020-03-01 19:33:41,857 INFO: 正在等待到达设定时间:2020-03-01 20:00:00.100000
2020-03-01 20:00:00,460 INFO: 时间到达，开始执行……
2020-03-01 20:00:00,584 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100006394713&sn=255b3779fbf2f5f2cb87eca726a7cfd7&from=pc
2020-03-01 20:00:00,584 INFO: 访问商品的抢购连接...
2020-03-01 20:00:00,673 INFO: 访问抢购订单结算页面...
2020-03-01 20:00:00,803 INFO: 生成提交抢购订单所需参数...
2020-03-01 20:00:00,804 INFO: 获取秒杀初始化信息...
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    start_tool.submit_seckill_order()
  File "D:\Workspace\VscodeProjects\jdBuyMask\daishu\jdMask_2\jd_mask_spider_requests.py", line 237, in submit_seckill_order
    self.seckill_order_data[self.sku_id] = self._get_seckill_order_data(
  File "D:\Workspace\VscodeProjects\jdBuyMask\daishu\jdMask_2\jd_mask_spider_requests.py", line 187, in _get_seckill_order_data
    self.seckill_init_info[self.sku_id] = self._get_seckill_init_info()
  File "D:\Workspace\VscodeProjects\jdBuyMask\daishu\jdMask_2\jd_mask_spider_requests.py", line 179, in _get_seckill_init_info
    return parse_json(resp.text)
  File "D:\Workspace\VscodeProjects\jdBuyMask\daishu\jdMask_2\util.py", line 63, in parse_json
    return json.loads(s[begin:end])
  File "C:\Software\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Software\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Software\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by helloqhq** [comment]
碰到了同样的问题

**Comment by ziwux** [comment]
我也是同样的问题

**Comment by yufeilai666** [comment]
同样的问题

**Comment by Lv-zhaoyang** [comment]
获取秒杀初始化信息:null， 没有获取到秒杀信息。

---

2020-03-02 19:30:01,010 INFO: 正在等待到达抢购设定时间:2020-03-02 20:00:00.100000
2020-03-02 20:00:00,387 INFO: 时间到达，开始执行……
2020-03-02 20:00:00,483 INFO: 抢购链接获取失败，不是抢购商品或抢购页面暂未刷新，1秒后重试
2020-03-02 20:00:01,593 INFO: 抢购链接获取成功: https://marathon.jd.com/captcha.html?skuId=100006394713&sn=be9818bbf6a0e24cfd3e88a49da9dc9b&from=pc
2020-03-02 20:00:01,593 INFO: 访问商品的抢购连接...
2020-03-02 20:00:01,695 INFO: 访问抢购订单结算页面...
2020-03-02 20:00:01,834 INFO: 生成提交抢购订单所需参数...
2020-03-02 20:00:01,835 INFO: 获取秒杀初始化信息...
2020-03-02 20:00:01,942 INFO: 获取秒杀初始化信息:null
